# Generated by Django 4.1.1 on 2022-10-04 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(unique=True, verbose_name='Номер заказа')),
                ('order_status', models.CharField(choices=[('SUCCESS', 'Успех'), ('TIMEOUT', 'Закрытие по таймауту'), ('CREATED_PAY', 'Создание транзакции'), ('FINISHED', 'Окончание транзакции'), ('PAID', 'Оплачивается')], default='PAID', max_length=11, verbose_name='Статус заказа')),
                ('order_description', models.CharField(max_length=1000, verbose_name='Описание заказа')),
                ('order_price', models.FloatField(default=0.0, verbose_name='Сумма к оплате')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='Время заказа')),
                ('signer_firstname', models.CharField(max_length=50, verbose_name='Фамилия заказчика')),
                ('signer_lastname', models.CharField(max_length=50, verbose_name='Имя заказчика')),
                ('signer_address', models.CharField(default='', max_length=500, verbose_name='Адрес доставки')),
                ('signer_phone', models.CharField(max_length=11, verbose_name='Контактный телефон')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_time'],
            },
        ),
    ]
