# Generated by Django 4.1.1 on 2022-09-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
